### PR TITLE
Add management command to support importing an entire WM media folder

### PR DESCRIPTION
**Pull request by MADindustries**

### CODE REVIEW

**Comment by MADindustries** [comment]
Don't merge this yet. Found a unicode issue within glob

**Comment by MADindustries** [comment]
Alright this should at least be good enough to merge and start accepting bug reports if things don't go quite right. Still some characters (like Japanese) that it seems to dislike even though it supports most unicode. Not really sure what's going on there

**Comment by MADindustries** [comment]
Alright it's happy with Japanese characters now and it will do its best to organize all errored torrents/data into subfolders named by the error that was encountered. This makes it very easy to go diagnose/fix by hand after all automated importing has finished

**Comment by OdinGitDat** [comment]
Using this atm to import old wm library. I got an unicode error for [651929](https://redacted.ch/torrents.php?id=6148&torrentid=651929). Have you tested with cyrillic characters?

Took me a while to figure out how to find the problematic torrent so I made a pull request for this command to make it easier. #126

**Pull request merged**
