### PR TITLE
Made the transcode page look like the other pages

### PR DESCRIPTION
**Pull request by davols**
0ymoao0n0ymoao0n

### CODE REVIEW

**Comment by MADindustries** [comment]
"Retry" button doesn't appear to be working here

**Comment by davols** [comment]
Merged in the css error and delete button from @MADindustries. Didn't add the link to the dashboard though.

**Comment by MADindustries** [comment]
Go look at the comments Kara left on my pull request. He says we don't actually need samba. So I'm going to remove it from mine in the next commit.

**Comment by karamanolev** [comment]
@davols This completely working? Can you just fix the samba error (we shouldn't include it at all, ever, anywhere) and we can merge this.

**Pull request closed without merging**
