### PR TITLE
Remove obsolete middleware

### PR DESCRIPTION
**Pull request by grandmasterchef**
Since we are using `django.contrib.auth.middleware.AuthenticationMiddleware` as our authentication provider, we don't need to use our own `HttpBasicAuthMiddleware`. 

In particular, I want to combine my whatmanager setup with an additional layer of authentication via apache's `AuthType Basic`, so that I can keep django's debug setting enabled while exposing the site to the world. The current middleware breaks this.

### CODE REVIEW

**Comment by karamanolev** [comment]
IIRC HttpBasicAuthMiddleware didn't work very well with curl credentials or something and therefore I had to write my own middleware.

**Comment by grandmasterchef** [comment]
yeah, I didn't have the cron set up until now, so I didn't need the middleware. Although really having a cron job curl a webpage with authentication is just messy, surely something like `./manage.py sync` would be much neater.

**Comment by karamanolev** [comment]
That's what I do now, but I didn't do that before, so it was all through
curl.

**Comment by grandmasterchef** [comment]
... but that command doesn't exist yet?

**Comment by karamanolev** [comment]
Those things that are implemented as HTTP endpoints aren't available as
manage.py commands yet. Feel free to add them.

**Comment by grandmasterchef** [comment]
I have a working version of a manage.py command, but it is so hackish I am embarrassed to push it :P I will do a more proper refactoring at some point, and then reopen here.

**Pull request closed without merging**
