### PR TITLE
Use OneToOne field instead of ForeignKey, Add delete torrent function to UI, Add Pipfile

### PR DESCRIPTION
**Pull request by MADindustries**

### CODE REVIEW

**Comment by karamanolev** [comment]
@MADindustries Let me know if you think this is ready to merge.

**Comment by MADindustries** [comment]
Should be good. I tested it prob 30 times different ways. It might need some better error handling at some point but I'm not totally sure what kinds of situations would cause those commands to fail yet. The button asks for confirmation before actually executing so it's unlikely anyone is going to destroy anything on accident. Should be good for at least a beta

**Comment by karamanolev** [comment]
@MADindustries Shouldn't people just do `migrate`?

**Comment by MADindustries** [comment]
Added in #114

**Pull request merged**
